routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);
Route::domain('{username}.final.widianapw.com')->group(function () {
    Route::get('/', 'ChatController@subdomain');
});
Route::group(['namespace' => 'AuthAdmin', 'prefix' => 'admin'], function () {
    Route::get('login', 'AdminAuthController@showLoginForm')->name('admin.login');
    Route::post('login', 'AdminAuthController@login')->name('admin.postlogin');
    Route::post('logout', 'AdminAuthController@logout')->name('admin.logout');
    Route::get('register', 'AdminAuthController@showRegisterForm')->name('admin.register');
    Route::post('register', 'AdminAuthController@register')->name('admin.postRegister');
});

Route::group(['namespace' => 'AuthSuperAdmin', 'prefix' => 'superadmin'], function () {
    Route::get('login', 'SuperAdminAuthController@showLoginForm')->name('superadmin.login');
    Route::post('login', 'SuperAdminAuthController@login')->name('superadmin.postlogin');
    Route::post('logout', 'SuperAdminAuthController@logout')->name('superadmin.logout');
});


Route::group(['middleware' => ['pengelola_jalan']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('digitasi-jalan', 'DigitasiJalanController');
    Route::post('/saveDigitasi', 'DigitasiJalanController@saveDigitasi');
    Route::resource('/pengaduan-jalan', 'PengaduanJalanController');
    Route::put('/pengaduan-jalan/change-status/{id}', 'PengaduanJalanController@changeStatus')->name('pengaduanJalan.changeStatus');
    Route::post('/pengaduan-jalan/add-image-terperbaiki', 'PengaduanJalanController@addTerperbaikiImages')->name('pengaduanJalan.addImageTerperbaiki');
});
Route::get('/verify-pengelola', 'HomeController@verifyPengelola')->name('verifypengelola')->middleware('verifiedPengelolaJalan');

Route::group(['middleware' => ['superadmin'], 'prefix' => 'superadmin'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('eksisting', 'EksistingController');
    Route::resource('jenis-jalan', 'JenisJalanController');
    // Route::post('/saveDigitasi','DigitasiJalanController@saveDigitasi');
    // Route::resource('/pengaduan-jalan','PengaduanJalanController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    // Route::resource('jenis-jalan', 'JenisJalanController');
    Route::resource('pengaduan-jalan', 'AdminPengaduanJalanController');
    Route::resource('validasi-digitasi-jalan', 'ValidasiDigitasiJalanController');
    Route::put('validasi-digitasi-jalan/verif/{id}', 'ValidasiDigitasiJalanController@verifDigitasi')->name('validasi-digitasi-jalan.verif');
    Route::put('validasi-digitasi-jalan/tolak/{id}', 'ValidasiDigitasiJalanController@tolakDigitasi')->name('validasi-digitasi-jalan.tolak');
    Route::get('validasi-digitasi-jalan/detail/{id}', 'ValidasiDigitasiJalanController@detailJalan');
    Route::resource('pengelola-jalan', 'PengelolaJalanController');
    Route::put('pengelola-jalan/verify/{pengelola_jalan}', 'PengelolaJalanController@changeStatus')->name('pengelola-jalan.changeStatus');
});


Route::get('/chat', 'ChatController@index');

Route::get('/pusher', function () {
    return view('pusher');
});

Route::get('/telegramBot', 'ChatController@telegeramBot');

app/JenisJalan.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class JenisJalan extends Model
{
    use SoftDeletes;
    protected $table = "jenis_jalans";
    protected $primaryKey = "id";
    protected $guarded = [];
//    public $with=['digitasiJalan'];
    public function digitasiJalan(){
        return $this->hasMany(DigitasiJalan::class, 'id_jenis_jalan');
    }

    public const VALIDATION_RULES = [
        "jenis_jalan" => "required|min:3"
    ];
}

app/Http/Controllers/JenisJalanController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\JenisJalanRequest;
use App\JenisJalan;
use Illuminate\Http\Request;

class JenisJalanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
       $data = JenisJalan::get();
       return view('superadmin.jenis_jalan.index', compact("data")); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('superadmin.jenis_jalan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JenisJalanRequest $request)
    {
        JenisJalan::insert($request->except(['_token']));
        return redirect('/superadmin/jenis-jalan')->with('success', $this->SUCCESS_ADD_MESSAGE);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\JenisJalan  $jenisJalan
     * @return \Illuminate\Http\Response
     */
    public function show(JenisJalan $jenisJalan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\JenisJalan  $jenisJalan
     * @return \Illuminate\Http\Response
     */
    public function edit(JenisJalan $jenisJalan)
    {
        return view("superadmin.jenis_jalan.edit", compact("jenisJalan"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\JenisJalan  $jenisJalan
     * @return \Illuminate\Http\Response
     */
    public function update(JenisJalanRequest $request, JenisJalan $jenisJalan)
    {
        JenisJalan::find($jenisJalan->id)->update($request->all());
        return redirect('/superadmin/jenis-jalan')->with('success', $this->SUCCESS_UPDATE_MESSAGE);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\JenisJalan  $jenisJalan
     * @return \Illuminate\Http\Response
     */
    public function destroy(JenisJalan $jenisJalan)
    {
        JenisJalan::find($jenisJalan->id)->delete();
        return redirect('/superadmin/jenis-jalan')->with('success', $this->SUCCESS_DELETE_MESSAGE);
    }
}

resources/views/superadmin/jenis_jalan/create.blade.php
@extends('layouts.layout')

@section('title','Tambah Jenis Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-orange">
            <div class="card-header">
                <h3 class="card-title">Jenis Jalan</h3>
            </div>
            <div class="card-body">
                <form action="{{route('jenis-jalan.store')}}" method="POST" class="form-group">
                    @csrf
                    <div class="form-body">
                        <div class="form-label">
                            <label for="nim">Jenis Jalan</label>
                        </div>
                        <input type="text" name="jenis_jalan" class="form-control">
                
                        <br>
                        <div class="form-footer">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/superadmin/jenis_jalan/edit.blade.php
@extends('layouts.layout')
@section('title','Edit Jenis Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-blue">
            <div class="card-header">
                <h3 class="card-title">Edit Jenis Jalan</h3>
            </div>
            <div class="card-body">
                <form action="/superadmin/jenis-jalan/{{$jenisJalan->id}}" method="POST" class="form-group">
                    @csrf
                    @method("PUT")
                    <div class="form-body">
                        <div class="form-label">
                            <label for="nim">Jenis Jalan</label>
                        </div>
                        <input type="text" name="jenis_jalan" class="form-control" value="{{$jenisJalan->jenis_jalan}}">
                
                        <br>
                            <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/superadmin/jenis_jalan/index.blade.php
@extends('layouts.layout')
@section('title','Jenis Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-green">
            <div class="card-header">
                <h3 class="card-title">Jenis Jalan</h3>
            </div>
        
        <div class="card-body ">
                <a href="{{route('jenis-jalan.create')}}">
                    <button class="btn btn-primary mb-4"><i class="fa fa-plus"></i>
                        Tambah Data
                    </button>
                </a>
            <div class="table-responsive">
            <table id="table-keuangan" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Jenis Jalan</th>
                        <th>Tanggal Dibuat</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $m)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $m->jenis_jalan }}</td>
                        <td>@dateFormat($m->created_at)</td>
                        <td>
                            <form action="{{route('jenis-jalan.edit',['jenis_jalan'=>$m->id])}}" method="GET">
                                @csrf
                                <button type="submit" class="btn btn-warning">
                                    <i class="fa fa-fw fa-edit" style="color:white"></i>
                                </button>
                            </form>
                        </td>
                        <td>
                            <form action="{{route('jenis-jalan.destroy',['jenis_jalan'=>$m->id])}}" method="POST">
                                @method("DELETE")
                                @csrf
                                <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-danger">
                                    <i class="fa fa-fw fa-trash"></i>
                                </button>
                            </form>
                        </td>    
                        
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
        </div>
    </div>
    </div>
</div>

@endsection
@section('js')
    <script>
        $(document).ready(function() {
            $('#table-keuangan').DataTable();
        });
    </script>
@endsection