routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);
Route::domain('{username}.final.widianapw.com')->group(function () {
    Route::get('/', 'ChatController@subdomain');
});
Route::group(['namespace' => 'AuthAdmin', 'prefix' => 'admin'], function () {
    Route::get('login', 'AdminAuthController@showLoginForm')->name('admin.login');
    Route::post('login', 'AdminAuthController@login')->name('admin.postlogin');
    Route::post('logout', 'AdminAuthController@logout')->name('admin.logout');
    Route::get('register', 'AdminAuthController@showRegisterForm')->name('admin.register');
    Route::post('register', 'AdminAuthController@register')->name('admin.postRegister');
});

Route::group(['namespace' => 'AuthSuperAdmin', 'prefix' => 'superadmin'], function () {
    Route::get('login', 'SuperAdminAuthController@showLoginForm')->name('superadmin.login');
    Route::post('login', 'SuperAdminAuthController@login')->name('superadmin.postlogin');
    Route::post('logout', 'SuperAdminAuthController@logout')->name('superadmin.logout');
});


Route::group(['middleware' => ['pengelola_jalan']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('digitasi-jalan', 'DigitasiJalanController');
    Route::post('/saveDigitasi', 'DigitasiJalanController@saveDigitasi');
    Route::resource('/pengaduan-jalan', 'PengaduanJalanController');
    Route::put('/pengaduan-jalan/change-status/{id}', 'PengaduanJalanController@changeStatus')->name('pengaduanJalan.changeStatus');
    Route::post('/pengaduan-jalan/add-image-terperbaiki', 'PengaduanJalanController@addTerperbaikiImages')->name('pengaduanJalan.addImageTerperbaiki');
});
Route::get('/verify-pengelola', 'HomeController@verifyPengelola')->name('verifypengelola')->middleware('verifiedPengelolaJalan');

Route::group(['middleware' => ['superadmin'], 'prefix' => 'superadmin'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('eksisting', 'EksistingController');
    Route::resource('jenis-jalan', 'JenisJalanController');
    // Route::post('/saveDigitasi','DigitasiJalanController@saveDigitasi');
    // Route::resource('/pengaduan-jalan','PengaduanJalanController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    // Route::resource('jenis-jalan', 'JenisJalanController');
    Route::resource('pengaduan-jalan', 'AdminPengaduanJalanController');
    Route::resource('validasi-digitasi-jalan', 'ValidasiDigitasiJalanController');
    Route::put('validasi-digitasi-jalan/verif/{id}', 'ValidasiDigitasiJalanController@verifDigitasi')->name('validasi-digitasi-jalan.verif');
    Route::put('validasi-digitasi-jalan/tolak/{id}', 'ValidasiDigitasiJalanController@tolakDigitasi')->name('validasi-digitasi-jalan.tolak');
    Route::get('validasi-digitasi-jalan/detail/{id}', 'ValidasiDigitasiJalanController@detailJalan');
    Route::resource('pengelola-jalan', 'PengelolaJalanController');
    Route::put('pengelola-jalan/verify/{pengelola_jalan}', 'PengelolaJalanController@changeStatus')->name('pengelola-jalan.changeStatus');
});


Route::get('/chat', 'ChatController@index');

Route::get('/pusher', function () {
    return view('pusher');
});

Route::get('/telegramBot', 'ChatController@telegeramBot');

app/Eksisting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Eksisting extends Model
{
    protected $table = "eksisting_jalans";
    protected $fillable = ["eksisting"];

    public const VALIDATION_RULES = [
        "eksisting" => "required|min:3"
    ];
    
}

app/Http/Controllers/EksistingController.php
<?php

namespace App\Http\Controllers;

use App\Eksisting;
use App\Http\Controllers\Controller;
use App\Http\Requests\EksistingRequest;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class EksistingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        $data = Eksisting::get();
        return view('superadmin.eksisting.index', compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('superadmin.eksisting.create');
    }

    public function store(EksistingRequest $request)
    {
        Eksisting::insert($request->except(['_token']));
        return redirect('/superadmin/eksisting')->with('success','Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Eksisting  $eksisting
     * @return Response
     */
    public function show(Eksisting $eksisting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Eksisting  $eksisting
     * @return Response
     */
    public function edit(Eksisting $eksisting)
    {
        return view('superadmin.eksisting.edit', compact("eksisting"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  \App\Eksisting  $eksisting
     * @return Response
     */
    public function update(EksistingRequest $request, Eksisting $eksisting)
    {
        Eksisting::find($eksisting->id)->update($request->all());
        return redirect('/superadmin/eksisting')->with('success','Data '.$eksisting->eksisting.' berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Eksisting  $eksistin
     * @return Response
     */
    public function destroy(Eksisting $eksisting)
    {
        Eksisting::find($eksisting->id)->delete();
        return redirect('/superadmin/eksisting')->with('success','Data berhasil dihapus');
    }
}

resources/views/superadmin/eksisting/create.blade.php
@extends('layouts.layout')

@section('title','Tambah Eksisting Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-orange">
            <div class="card-header">
                <h3 class="card-title">Eksisting Jalan</h3>
            </div>
            <div class="card-body">
                <form action="{{route('eksisting.store')}}" method="POST" class="form-group">
                    @csrf
                    <div class="form-body">
                        <div class="form-label">
                            <label for="nim">Eksisting Jalan</label>
                        </div>
                        <input type="text" name="eksisting" class="form-control">
                
                        <br>
                        <div class="form-footer">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/superadmin/eksisting/edit.blade.php
@extends('layouts.layout')
@section('title','Edit Eksisting Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-blue">
            <div class="card-header">
                <h3 class="card-title">Edit Eksisting Jalan</h3>
            </div>
            <div class="card-body">
                <form action="{{route('eksisting.update',['eksisting'=> $eksisting->id])}}" method="POST" class="form-group">
                    @csrf
                    @method("PUT")
                    <div class="form-body">
                        <div class="form-label">
                            <label for="nim">Eksisting Jalan</label>
                        </div>
                        <input type="text" name="eksisting" class="form-control" value="{{$eksisting->eksisting}}">
                
                        <br>
                            <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/superadmin/eksisting/index.blade.php
@extends('layouts.layout')
@section('title','Eksisting Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-green">
            <div class="card-header">
                <h3 class="card-title">Eksisting Jalan</h3>
            </div>
        
        <div class="card-body ">
                <a href="{{route('eksisting.create')}}">
                    <button class="btn btn-primary mb-4"><i class="fa fa-plus"></i>
                        Tambah Data
                    </button>
                </a>
            <div class="table-responsive">
            <table id="table-keuangan" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Eksisting Jalan</th>
                        <th>Tanggal Dibuat</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $m)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $m->eksisting }}</td>
                        <td>@dateFormat($m->created_at)</td>
                        <td>
                            <a href="{{route('eksisting.edit',['eksisting'=>$m->id])}}">
                                <button class="btn btn-warning">
                                    <i class="fa fa-fw fa-edit" style="color:white"></i>
                                </button>
                            </a>
                        </td>
                        <td>
                            <form action="{{route('eksisting.destroy',['eksisting'=>$m->id])}}" method="POST">
                                @method("DELETE")
                                @csrf
                                <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-danger">
                                    <i class="fa fa-fw fa-trash"></i>
                                </button>
                            </form>
                        </td>    
                        
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
        </div>
    </div>
    </div>
</div>

@endsection
@section('js')
    <script>
        $(document).ready(function() {
            $('#table-keuangan').DataTable();
        });
    </script>
@endsection