routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);
Route::domain('{username}.final.widianapw.com')->group(function () {
    Route::get('/', 'ChatController@subdomain');
});
Route::group(['namespace' => 'AuthAdmin', 'prefix' => 'admin'], function () {
    Route::get('login', 'AdminAuthController@showLoginForm')->name('admin.login');
    Route::post('login', 'AdminAuthController@login')->name('admin.postlogin');
    Route::post('logout', 'AdminAuthController@logout')->name('admin.logout');
    Route::get('register', 'AdminAuthController@showRegisterForm')->name('admin.register');
    Route::post('register', 'AdminAuthController@register')->name('admin.postRegister');
});

Route::group(['namespace' => 'AuthSuperAdmin', 'prefix' => 'superadmin'], function () {
    Route::get('login', 'SuperAdminAuthController@showLoginForm')->name('superadmin.login');
    Route::post('login', 'SuperAdminAuthController@login')->name('superadmin.postlogin');
    Route::post('logout', 'SuperAdminAuthController@logout')->name('superadmin.logout');
});


Route::group(['middleware' => ['pengelola_jalan']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('digitasi-jalan', 'DigitasiJalanController');
    Route::post('/saveDigitasi', 'DigitasiJalanController@saveDigitasi');
    Route::resource('/pengaduan-jalan', 'PengaduanJalanController');
    Route::put('/pengaduan-jalan/change-status/{id}', 'PengaduanJalanController@changeStatus')->name('pengaduanJalan.changeStatus');
    Route::post('/pengaduan-jalan/add-image-terperbaiki', 'PengaduanJalanController@addTerperbaikiImages')->name('pengaduanJalan.addImageTerperbaiki');
});
Route::get('/verify-pengelola', 'HomeController@verifyPengelola')->name('verifypengelola')->middleware('verifiedPengelolaJalan');

Route::group(['middleware' => ['superadmin'], 'prefix' => 'superadmin'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('eksisting', 'EksistingController');
    Route::resource('jenis-jalan', 'JenisJalanController');
    // Route::post('/saveDigitasi','DigitasiJalanController@saveDigitasi');
    // Route::resource('/pengaduan-jalan','PengaduanJalanController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    // Route::resource('jenis-jalan', 'JenisJalanController');
    Route::resource('pengaduan-jalan', 'AdminPengaduanJalanController');
    Route::resource('validasi-digitasi-jalan', 'ValidasiDigitasiJalanController');
    Route::put('validasi-digitasi-jalan/verif/{id}', 'ValidasiDigitasiJalanController@verifDigitasi')->name('validasi-digitasi-jalan.verif');
    Route::put('validasi-digitasi-jalan/tolak/{id}', 'ValidasiDigitasiJalanController@tolakDigitasi')->name('validasi-digitasi-jalan.tolak');
    Route::get('validasi-digitasi-jalan/detail/{id}', 'ValidasiDigitasiJalanController@detailJalan');
    Route::resource('pengelola-jalan', 'PengelolaJalanController');
    Route::put('pengelola-jalan/verify/{pengelola_jalan}', 'PengelolaJalanController@changeStatus')->name('pengelola-jalan.changeStatus');
});


Route::get('/chat', 'ChatController@index');

Route::get('/pusher', function () {
    return view('pusher');
});

Route::get('/telegramBot', 'ChatController@telegeramBot');

app/DigitasiJalan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DigitasiJalan extends Model
{
    use SoftDeletes;
    protected $table = "digitasi_jalans";
    protected $primaryKey = "id";
    protected $guarded = [];
    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($digitasiJalans) {
            foreach ($digitasiJalans->pengaduan()->get() as $item) {
                $item->delete();
            }
        });
    }
    public $with = ['jenisjalan', 'eksistingJalan', 'pengelolaJalan', 'detailDigitasi'];
    public function detailDigitasi()
    {
        return $this->hasMany(KoordinatDigitasiJalan::class, 'id_digitasi_jalan');
    }
    public function jenisJalan()
    {
        return $this->belongsTo(JenisJalan::class, 'id_jenis_jalan');
    }

    public function eksistingJalan()
    {
        return $this->belongsTo(Eksisting::class, 'id_eksisting');
    }

    public function pengelolaJalan()
    {
        return $this->belongsTo(PengelolaJalan::class, 'id_pengelola_jalan');
    }

    public function pengaduan()
    {
        return $this->hasMany(PengaduanJalan::class, 'id_digitasi_jalan');
    }


    public static function getJalanStatus($key)
    {
        if ($key == "0") {
            return "Menunggu Verifikasi";
        } else if ($key == "1") {
            return "Terverifikasi";
        } else {
            return "Ditolak";
        }
    }

    public const VALIDATION_RULES = [
        "id_jenis_jalan" => "required",
        "nama_jalan" => "required|min:5",
        "ruas_jalan" => "required|min:5",
        "panjang_ruas" => "required|numeric|min:0.1",
        "lebar_ruas" => "required|numeric|min:0.1",
        "id_eksisting" => "required"
    ];
}

app/PengelolaJalan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PengelolaJalan extends Model
{
    use SoftDeletes;

    protected $table = "pengelola_jalans";
    protected $guarded = [];

    protected $with= ['user','provinsi','kabupaten','desa'];

    public function user()
    {
        return $this->belongsTo(User::class, 'id_user');
    }

    public function provinsi()
    {
        return $this->belongsTo(Provinsi::class, 'id_provinsi');
    }

    public function kabupaten()
    {
        return $this->belongsTo(Kabupaten::class, 'id_kabupaten');
    }

    public function desa()
    {
        return $this->belongsTo(Desa::class, 'id_desa');
    }

    public function jenisJalan()
    {
        return $this->belongsTo(JenisJalan::class, 'id_jenis_jalan');
    }
}

app/Http/Controllers/API/DigitasiJalanController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\DigitasiJalan;
use App\Http\Resources\DigitasiResourceCollection;
use App\Http\Resources\DigitasiResource;

class DigitasiJalanController extends Controller
{
    public function index(){
        $digitasiJalan = DigitasiJalan::where('status','1')->get();
        // return $digitasiJalan;
        return new DigitasiResourceCollection($digitasiJalan);
    }
}

app/Http/Controllers/DigitasiJalanController.php
<?php

namespace App\Http\Controllers;

use App\DigitasiJalan;
use App\JenisJalan;
use App\KoordinatDigitasiJalan;
use App\User;
use Illuminate\Http\Request;
use Auth;
use App\Kabupaten;
use App\Desa;
use App\Eksisting;
use App\Http\Requests\DigitasiJalanRequest;
use App\PengelolaJalan;

class DigitasiJalanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $view = "pengelola_jalan.digitasi_jalan.";
    public function index()
    {
//        $digitasiJalan = DigitasiJalan::get();
//        $pengelolaJalan = UserResource::where('id',Auth::user()->id)->get();
        $data = DigitasiJalan::where('id_pengelola_jalan', Auth::user()->pengelolaJalan->id)->orderBy("id","desc")->get();
        // $dataTerverifikasi = DigitasiJalan::with('jenisJalan')->where('id_pengelola_jalan',Auth::user()->pengelolaJalan->id)->where('status','1')->orderBy('id','desc')->get();
        // $dataDitolak = DigitasiJalan::with('jenisJalan')->where('id_pengelola_jalan',Auth::id())->where('status','2')->orderBy('id','desc')->get();
        return view($this->view."index", compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jenisJalan = JenisJalan::get();
        $eksisting = Eksisting::get();
        $user = PengelolaJalan::with('jenisJalan','user','provinsi','kabupaten','desa')->whereHas('user', function($query){
            return $query->where('id', Auth::id());
        })->first();
        $jenis = strtolower($user->jenisJalan->jenis_jalan);
        $validasi = "";
        if($jenis == "kabupaten" || $jenis == "kota"){
            $validasi = Kabupaten::with('provinsi')->where('id',$user->id_kabupaten)->first();
        }if($jenis == "desa"){
            $validasi = Desa::with('kecamatan')->where('id',$user->id_desa)->first();
        }
        return view($this->view."create", compact("jenisJalan","eksisting","user","validasi"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DigitasiJalanRequest $request)
    {
        $pengelolaJalan = PengelolaJalan::where('id_user', Auth::id())->first();
        if($request->isEdit){
            $digitasiJalan = DigitasiJalan::where('id',$request->id_jalan)->first();
            $detail = KoordinatDigitasiJalan::where('id_digitasi_jalan',$request->id_jalan)->get();
            $detail->each->delete();
        }else{
            $digitasiJalan = new DigitasiJalan;
        }
        $digitasiJalan->id_pengelola_jalan = $pengelolaJalan->id;
        $digitasiJalan->nama_jalan = $request->nama_jalan;
        $digitasiJalan->ruas_jalan = $request->ruas_jalan;
        $digitasiJalan->panjang_ruas = $request->panjang_ruas;
        $digitasiJalan->lebar_ruas = $request->lebar_ruas;
        $digitasiJalan->id_jenis_jalan = $request->id_jenis_jalan;
        $digitasiJalan->id_eksisting = $request->id_eksisting;
        $digitasiJalan->save();
        foreach ($request->koordinat as $item) {
            $detailKoordinat = new KoordinatDigitasiJalan;
            $detailKoordinat->id_digitasi_jalan = $digitasiJalan->id;
            $detailKoordinat->latitude = $item['lat'];
            $detailKoordinat->longitude = $item['lng'];
            $detailKoordinat->save();
        }
        return response()->json(['success'=>'Got Simple Ajax Request.']);
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DigitasiJalan  $digitasiJalan
     * @return \Illuminate\Http\Response
     */
    public function show(DigitasiJalan $digitasiJalan)
    {

        return $digitasiJalan->detailDigitasi;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DigitasiJalan  $digitasiJalan
     * @return \Illuminate\Http\Response
     */
    public function edit(DigitasiJalan $digitasiJalan)
    {
        // return $digitasiJalan;
        $jenisJalan = JenisJalan::get();
        $eksisting = Eksisting::get();
        $user = PengelolaJalan::with('jenisJalan','user','provinsi','kabupaten','desa')->whereHas('user', function($query){
            return $query->where('id', Auth::id());
        })->first();
        $jenis = strtolower($user->jenisJalan->jenis_jalan);
        $validasi = "";
        if($jenis == "kabupaten" || $jenis == "kota"){
            $validasi = Kabupaten::with('provinsi')->where('id',$user->id_kabupaten)->first();
        }if($jenis == "desa"){
            $validasi = Desa::with('kecamatan')->where('id',$user->id_desa)->first();
        }
        return view($this->view."create", compact("digitasiJalan","jenisJalan","eksisting","user","validasi"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\DigitasiJalan  $digitasiJalan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, DigitasiJalan $digitasiJalan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DigitasiJalan  $digitasiJalan
     * @return \Illuminate\Http\Response
     */
    public function destroy(DigitasiJalan $digitasiJalan)
    {
        DigitasiJalan::find($digitasiJalan->id)->delete();
        return redirect('/digitasi-jalan')->with('success', $this->SUCCESS_DELETE_MESSAGE);
    }
}

app/Http/Controllers/PengelolaJalanController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\User;
use App\Admin;
use Carbon\Carbon;

use App\PengelolaJalan;
use Illuminate\Http\Request;

class PengelolaJalanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admin = Admin::where('id_user',Auth::id())->first();
        if($admin->id_jenis_jalan == "1" ){
            $data = PengelolaJalan::with('user','provinsi','kabupaten','desa','jenisJalan')->where('id_jenis_jalan',$admin->id_jenis_jalan)->where('id_provinsi',$admin->id_provinsi)->get();     
        }else if($admin->id_jenis_jalan == "3"|| $admin->id_jenis_jalan == "2" ){
            $data = PengelolaJalan::with('user','provinsi','kabupaten','desa','jenisJalan')->where('id_jenis_jalan',$admin->id_jenis_jalan)->where('id_kabupaten',$admin->id_kabupaten)->get();     
        }else if($admin->id_jenis_jalan == "4"){
            $data = PengelolaJalan::with('user','provinsi','kabupaten','desa','jenisJalan')->where('id_jenis_jalan',$admin->id_jenis_jalan)->where('id_desa',$admin->id_desa)->get();     
        }
        return view("admin.pengelola_jalan.index",compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PengelolaJalan  $pengelolaJalan
     * @return \Illuminate\Http\Response
     */
    public function show(PengelolaJalan $pengelolaJalan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PengelolaJalan  $pengelolaJalan
     * @return \Illuminate\Http\Response
     */
    public function edit(PengelolaJalan $pengelolaJalan)
    {
        return view("admin.pengelola_jalan.edit");
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PengelolaJalan  $pengelolaJalan
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, PengelolaJalan $pengelolaJalan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PengelolaJalan  $pengelolaJalan
     * @return \Illuminate\Http\Response
     */
    public function destroy(PengelolaJalan $pengelolaJalan)
    {
        //
    }

    public function changeStatus(PengelolaJalan $pengelolaJalan, Request $request){
        $user = PengelolaJalan::find($pengelolaJalan->id);
        $user->verified = Carbon::now();
        $user->update();
        return \redirect()->back()->with("success",$this->SUCCESS_UPDATE_MESSAGE);
    }
}

resources/views/pengelola_jalan/digitasi_jalan/create.blade.php
@extends('layouts.layout')
@section('title', 'Tambah Digitasi Jalan')
@section('content')
    <div>
        <div class="row pt-2">
            <div class="col-md-12">
                <div class="card card-blue">
                    <div class="card-header">
                        <h3 class="card-title">
                            @if (!empty($digitasiJalan))Ubah @else Tambah @endif Digitasi Jalan
                        </h3>
                    </div>
                    <div class="alert alert-danger alert-dismissible m-3" id="error-alert" style="display: none">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h5><i class="icon fas fa-times"></i> Validation!</h5>
                        <div style="white-space: pre-line" id="error_messages">

                        </div>
                    </div>
                    <div class="card-body">
                        <div class="callout callout-info">
                            <h4>Informasi Penambahan Digitasi Jalan</h4>
                            <p>*Dapat menambahkan digitasi jalan dengan import data dalam CSV <a
                                    href="{{ asset('/file/format_digitasi_jalan.csv') }}">Sesuai Format</a> atau
                                menggambar pada peta<br>
                                *Klik kiri pada peta untuk menambah titik jalan <br>
                                *Klik kanan pada titik jalan untuk menghapus <br>
                            </p><a href="{{ asset('/file/format_digitasi_jalan.csv') }}">Download Format CSV Digitasi
                                Jalan</a>

                        </div>
                        <div class="d-flex justify-content-start">
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#importModal"
                                data-backdrop="static" data-keyboard="false">+ Import dari CSV
                            </button>
                        </div>
                        <div id="dvCSV">
                            <br>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-search"></i></span>
                                </div>
                                <input type="text" class="form-control" id="search" placeholder="Cari Jalan...">
                            </div>

                            <div id="mapKu" class="mt-3"></div>
                            <hr>
                            @if (!empty($digitasiJalan))
                                <input type="hidden" id="id_jalan" value="{{ $digitasiJalan->id }}">
                            @endif
                            <label for="nama_jalan">Jenis Jalan</label>
                            <input type="hidden" class="form-control" id="id_jenis_jalan"
                                value="{{ $user->jenisJalan->id }}">
                            <input type="text" class="form-control" id="jenis_jalan"
                                value="{{ $user->jenisJalan->jenis_jalan }}" readonly>
                            @php
                                $jenisJalan = strtolower($user->jenisJalan->jenis_jalan);
                            @endphp
                            @if ($jenisJalan == 'kabupaten' || $jenisJalan == 'kota')
                                <input type="hidden" class="form-control" id="provinsi"
                                    value="{{ $validasi->provinsi->provinsi }}" readonly>
                            @elseif($jenisJalan == "desa")
                                <input type="hidden" class="form-control" id="kecamatan"
                                    value="{{ $validasi->kecamatan->kecamatan }}" readonly>
                            @endif
                            <br>
                            <label for="nama_jalan">Nama Jalan</label>
                            <input type="text" class="form-control" id="nama_jalan" @if (!empty($digitasiJalan)) value="{{ $digitasiJalan->nama_jalan }}" @endif>
                            <br>
                            <label for="ruas_jalan">Ruas Jalan</label>
                            <input type="text" class="form-control" id="ruas_jalan" @if (!empty($digitasiJalan)) value="{{ $digitasiJalan->ruas_jalan }}" @endif>
                            <br>
                            <label for="nama_jalan">Panjang Ruas</label>
                            <div class="input-group">
                                <input type="number" step="any" class="form-control" id="panjang_ruas" @if (!empty($digitasiJalan)) value="{{ $digitasiJalan->panjang_ruas }}" @endif
                                    readonly>
                                <div class="input-group-append">
                                    <div class="input-group-text">Meter</div>
                                </div>
                            </div>
                            <br>
                            <label for="nama_jalan">Lebar Ruas</label>
                            <div class="input-group">
                                <input type="number" step="any" class="form-control" id="lebar_ruas" @if (!empty($digitasiJalan)) value="{{ $digitasiJalan->lebar_ruas }}" @endif>
                                <div class="input-group-append">
                                    <div class="input-group-text">Meter</div>
                                </div>
                            </div>
                            <br>
                            <label for="eksisting">Eksisting Jalan</label>
                            <select name="id_eksisting" class="form-control" id="id_eksisting">
                                <option value="">Pilih Eksisting Jalan</option>
                                @foreach ($eksisting as $e)
                                    @if (!empty($digitasiJalan))
                                        @if ($e->id == $digitasiJalan->id_eksisting)
                                            <option value="{{ $e->id }}" selected>{{ $e->eksisting }}</option>
                                        @else
                                            <option value="{{ $e->id }}">{{ $e->eksisting }}</option>
                                        @endif
                                    @else
                                        <option value="{{ $e->id }}">{{ $e->eksisting }}</option>
                                    @endif
                                @endforeach
                            </select>
                            <br>
                            @if (!empty($digitasiJalan))
                                <button type="submit" id="update" class="btn btn-warning">Ubah</button>
                            @else
                                <button type="submit" id="submit" class="btn btn-success">Tambah</button>
                            @endif
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal fade" id="importModal">
                <div class="modal-dialog modal-dialog-centered" ">
                                <div class=" modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Import CSV</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">

                        <input type="file" id="csvFile" class="form-control" accept=".csv">
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="button" id="btnImport" class="btn btn-success">Import</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
    </div>
@endsection
@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{{ asset('/js/digitasi-jalan.js') }}"></script>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYsDrPWaL32zuvMCQ-8lely3pQ0MWjv4o&libraries=places,geometry&callback=initMap"
        async defer></script>
@endsection

resources/views/pengelola_jalan/digitasi_jalan/index.blade.php
@extends('layouts.layout')
@section('title','Digitasi Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">

        <div class="card card-blue">
            <div class="card-header">
                <h3 class="card-title">Digitasi Jalan yang anda Kelola</h3>
            </div>
            <div class="card-body">
                <a href="/digitasi-jalan/create">
                    <button class="btn btn-primary mb-4"><i class="fa fa-plus"></i>
                        Tambah Data Jalan
                    </button>
                </a>


                <div class="table-responsive">
                    <table id="table-data" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama</th>
                                <th>Ruas Jalan</th>
                                <th>Panjang Ruas</th>
                                <th>Lebar Ruas</th>
                                <th>Status</th>
                                <th>Tanggal</th>
                                <th>Edit</th>
                                <th>Delete</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $m)

                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $m->nama_jalan }}</td>
                                <td>{{$m->ruas_jalan}}</td>
                                <td>{{$m->panjang_ruas}} Meter</td>
                                <td>{{$m->lebar_ruas}} Meter</td>
                                <td>{{ \App\DigitasiJalan::getJalanStatus($m->status) }}</td>
                                <td>@dateFormat($m->created_at)</td>

                                <td>
                                    <a href="/digitasi-jalan/{{$m->id}}/edit"><button type="submit" class="btn btn-warning">
                                        <i class="fa fa-fw fa-edit" style="color:white"></i>
                                    </button></a>
                                </td>
                                <td>
                                <form action="{{route('digitasi-jalan.destroy',['digitasi_jalan'=>$m])}}" method="POST">
                                        @method("DELETE")
                                        @csrf
                                        <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-danger">
                                            <i class="fa fa-fw fa-trash"></i>
                                        </button>
                                    </form>
                                </td>


                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script>
    $(document).ready(function() {
        $('#table-data').DataTable();
    });
</script>

@endsection