routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);
Route::domain('{username}.final.widianapw.com')->group(function () {
    Route::get('/', 'ChatController@subdomain');
});
Route::group(['namespace' => 'AuthAdmin', 'prefix' => 'admin'], function () {
    Route::get('login', 'AdminAuthController@showLoginForm')->name('admin.login');
    Route::post('login', 'AdminAuthController@login')->name('admin.postlogin');
    Route::post('logout', 'AdminAuthController@logout')->name('admin.logout');
    Route::get('register', 'AdminAuthController@showRegisterForm')->name('admin.register');
    Route::post('register', 'AdminAuthController@register')->name('admin.postRegister');
});

Route::group(['namespace' => 'AuthSuperAdmin', 'prefix' => 'superadmin'], function () {
    Route::get('login', 'SuperAdminAuthController@showLoginForm')->name('superadmin.login');
    Route::post('login', 'SuperAdminAuthController@login')->name('superadmin.postlogin');
    Route::post('logout', 'SuperAdminAuthController@logout')->name('superadmin.logout');
});


Route::group(['middleware' => ['pengelola_jalan']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('digitasi-jalan', 'DigitasiJalanController');
    Route::post('/saveDigitasi', 'DigitasiJalanController@saveDigitasi');
    Route::resource('/pengaduan-jalan', 'PengaduanJalanController');
    Route::put('/pengaduan-jalan/change-status/{id}', 'PengaduanJalanController@changeStatus')->name('pengaduanJalan.changeStatus');
    Route::post('/pengaduan-jalan/add-image-terperbaiki', 'PengaduanJalanController@addTerperbaikiImages')->name('pengaduanJalan.addImageTerperbaiki');
});
Route::get('/verify-pengelola', 'HomeController@verifyPengelola')->name('verifypengelola')->middleware('verifiedPengelolaJalan');

Route::group(['middleware' => ['superadmin'], 'prefix' => 'superadmin'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('eksisting', 'EksistingController');
    Route::resource('jenis-jalan', 'JenisJalanController');
    // Route::post('/saveDigitasi','DigitasiJalanController@saveDigitasi');
    // Route::resource('/pengaduan-jalan','PengaduanJalanController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    // Route::resource('jenis-jalan', 'JenisJalanController');
    Route::resource('pengaduan-jalan', 'AdminPengaduanJalanController');
    Route::resource('validasi-digitasi-jalan', 'ValidasiDigitasiJalanController');
    Route::put('validasi-digitasi-jalan/verif/{id}', 'ValidasiDigitasiJalanController@verifDigitasi')->name('validasi-digitasi-jalan.verif');
    Route::put('validasi-digitasi-jalan/tolak/{id}', 'ValidasiDigitasiJalanController@tolakDigitasi')->name('validasi-digitasi-jalan.tolak');
    Route::get('validasi-digitasi-jalan/detail/{id}', 'ValidasiDigitasiJalanController@detailJalan');
    Route::resource('pengelola-jalan', 'PengelolaJalanController');
    Route::put('pengelola-jalan/verify/{pengelola_jalan}', 'PengelolaJalanController@changeStatus')->name('pengelola-jalan.changeStatus');
});


Route::get('/chat', 'ChatController@index');

Route::get('/pusher', function () {
    return view('pusher');
});

Route::get('/telegramBot', 'ChatController@telegeramBot');

app/PengaduanJalan.php
<?php

namespace App;

use Illuminate\Support\Facades\Auth;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class PengaduanJalan extends Model
{
    use SoftDeletes, Notifiable;

    protected $table = "pengaduan_jalans";
    protected $fillable = [
        "id_digitasi_jalan",
        "id_user",
        "foto_url",
        "deskripsi",
        "status"
    ];

    public $with = ['pengguna', 'digitasiJalan', 'pengaduanLog', 'images'];

    public function digitasiJalan()
    {
        return $this->belongsTo(DigitasiJalan::class, 'id_digitasi_jalan');
    }

    public function pengguna()
    {
        return $this->belongsTo(Pengguna::class, 'id_pengguna');
    }

    public function pengaduanLog()
    {
        return $this->hasMany(PengaduanLog::class, 'id_pengaduan');
    }

    public function images()
    {
        return $this->hasMany(PengaduanImage::class, 'id_pengaduan');
    }

    public static function getStatusPengaduan($key)
    {
        if ($key == "0") {
            return "Menunggu Verifikasi";
        } else if ($key == "1") {
            return "Terverifikasi";
        } else if ($key == "2") {
            return "Terperbaiki";
        } else {
            return "Ditolak";
        }
    }
}

app/Http/Controllers/PengaduanJalanController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\PengaduanImage;
use App\PengaduanJalan;
use Illuminate\Http\Request;

class PengaduanJalanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = PengaduanJalan::where('status', '0')->whereHas('digitasiJalan', function ($query) {
            return $query->where('id_pengelola_jalan', '=', Auth::user()->pengelolaJalan->id);
        })->orderBy('id', 'desc')->get();
        $dataTerverifikasi = PengaduanJalan::where('status', '1')->whereHas('digitasiJalan', function ($query) {
            return $query->where('id_pengelola_jalan', '=', Auth::user()->pengelolaJalan->id);
        })->orderBy('id', 'desc')->get();
        $dataSudahDiperbaiki = PengaduanJalan::where('status', '2')->whereHas('digitasiJalan', function ($query) {
            return $query->where('id_pengelola_jalan', '=', Auth::user()->pengelolaJalan->id);
        })->orderBy('id', 'desc')->get();
        $dataDitolak = PengaduanJalan::where('status', '3')->whereHas('digitasiJalan', function ($query) {
            return $query->where('id_pengelola_jalan', '=', Auth::user()->pengelolaJalan->id);
        })->orderBy('id', 'desc')->get();
        // return $data;
        return view("pengelola_jalan.pengaduan_jalan.index", compact("data", "dataTerverifikasi", "dataSudahDiperbaiki", "dataDitolak"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $request['id_bengkel'] = Auth::user()->id_bengkel;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PengaduanJalan  $pengaduanJalan
     * @return \Illuminate\Http\Response
     */
    public function show(PengaduanJalan $pengaduanJalan)
    {
        $data = PengaduanJalan::find($pengaduanJalan->id);
        return view("pengelola_jalan.pengaduan_jalan.detail", compact("data"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PengaduanJalan  $pengaduanJalan
     * @return \Illuminate\Http\Response
     */
    public function edit(PengaduanJalan $pengaduanJalan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PengaduanJalan  $pengaduanJalan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PengaduanJalan $pengaduanJalan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PengaduanJalan  $pengaduanJalan
     * @return \Illuminate\Http\Response
     */
    public function destroy(PengaduanJalan $pengaduanJalan)
    {
        //
    }

    public function changeStatus(Request $request, $id)
    {
        $jalan = PengaduanJalan::find($id);
        $jalan->status = $request->status;
        $jalan->update();
        return redirect()->back()->with("success", "Status Pengaduan Berhasil Diubah!");
    }

    public function addTerperbaikiImages(Request $request)
    {
        $jalan = PengaduanJalan::find($request->id_pengaduan);
        $jalan->status = "2";
        $jalan->update();
        if ($request->hasfile('foto_terperbaiki')) {
            foreach ($request->file('foto_terperbaiki') as $file) {
                $name = uniqid() . '.png';
                $file->move(public_path() . "/img/jalan-rusak/", $name);
                $hasil[] = $name;
                $file = new PengaduanImage();
                $file->id_pengaduan = $request->id_pengaduan;
                $file->type = "terperbaiki";
                $file->foto_url = $name;
                $file->save();
            }
        }
        return redirect()->back()->with("success", "Status Pengaduan Berhasil Diubah!");
    }
}

resources/views/admin/pengaduan_jalan/index.blade.php
@extends('layouts.layout')
@section('title','Pengaduan Jalan')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-blue">
            <div class="card-header">
                <h3 class="card-title">Pengaduan Jalan</h3>
            </div>
            <div class="card-body">
                <div class="table-responsive tab-pane active p-3" id="belum">
                    <table id="table-data" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Jalan</th>
                                <th>Ruas Jalan</th>
                                <th>Nama Pengadu</th>
                                <th>Deskripsi</th>
                                <th>Status</th>
                                <th>Tanggal</th>
                                <th>Lihat Detail</th>
                                {{-- <th>Beri Komentar</th> --}}
                                {{-- <th>Aksi</th> --}}

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $m)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $m->digitasiJalan->nama_jalan }}</td>
                                <td>{{$m->digitasiJalan->ruas_jalan}}</td>
                                <td>{{ $m->pengguna->user->username }}</td>
                                <td>{{$m->deskripsi}}</td>
                                <td>
                                    {{ \App\PengaduanJalan::getStatusPengaduan($m->status) }}
                                </td>
                                <td>@dateFormat($m->created_at)</td>
                                <td>
                                    <a href="{{route('admin.pengaduan-jalan.show',['pengaduan_jalan'=>$m->id])}}">
                                        <button class="btn btn-primary"><i class="fa fa-eye"></i></button>
                                    </a>
                                </td>

                                {{-- <td>
                                        <button type="button" class="btn btn-info" data-toggle="modal"
                                                data-target="#komentarModal">
                                            Komentar
                                        </button>
                                    </td> --}}
                                {{-- <td>
                                    <div class="btn-group">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-warning dropdown-toggle"
                                                data-toggle="dropdown">
                                                Aksi
                                            </button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item"
                                                    href="{{route("pengaduanJalan.changeStatus",["id"=>$m->id])}}"
                                                    onclick="event.preventDefault(); document.getElementById('status-{{ $m->id }}').value='1'; document.getElementById('changeStatusForm-{{ $m->id }}').submit() ">Verifikasi</a>
                                                <a class="dropdown-item"
                                                    href="{{route("pengaduanJalan.changeStatus",["id"=>$m->id])}}"
                                                    onclick="event.preventDefault(); document.getElementById('status-{{ $m->id }}').value='2'; document.getElementById('changeStatusForm-{{ $m->id }}').submit() ">Terberpaiki</a>
                                                <a class="dropdown-item"
                                                    href="{{route("pengaduanJalan.changeStatus",["id"=>$m->id])}}"
                                                    onclick="event.preventDefault(); document.getElementById('status-{{ $m->id }}').value='3'; document.getElementById('changeStatusForm-{{ $m->id }}').submit() ">Tolak</a>

                                                <form id="changeStatusForm-{{ $m->id }}"
                                                    action="{{route("pengaduanJalan.changeStatus",["id"=>$m->id])}}"
                                                    method="POST" style="display: none">
                                                    @csrf
                                                    @method("PUT")
                                                    <input type="hidden" id="status-{{ $m->id }}" name="status"
                                                        value="1">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td> --}}

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                    


                
            </div>
        </div>
    </div>

    <div class="modal fade" id="komentarModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Komentar</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <form action="#">

                        <input type="text" id="komentar" class="form-control" required name="komentar">
                        <br>
                        <button type="submit" class="btn btn-primary">Kirim Komentar</button>
                    </form>
                </div>

            </div>
        </div>
    </div>


</div>
@endsection
@section('js')
<script>
    $(document).ready(function () {
            $('#table-data').DataTable();
        });
</script>

@endsection